/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View;
import Controller.LibrosDAO;
import Model.Libros;
import javax.swing.JOptionPane;
/**
 *
 * @author Dell
 */
public class FormularioLibros extends javax.swing.JDialog {
    private String mode;
    private int LibrosID;
    private LibrosDAO dao;
    private ListadoLibros parent;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormularioLibros.class.getName());

    /**
     * Creates new form FormularioLibros
     */
    public FormularioLibros(ListadoLibros pParent, boolean modal, String pMode, int pLibrosID){
        super(pParent, modal);
        this.parent = pParent;
        initComponents();
        setLocationRelativeTo(null);
        
        dao = new LibrosDAO();
        this.mode = pMode;
        this.LibrosID = pLibrosID;
        txt_LibrosID.setText(String.valueOf(pLibrosID));
        if(mode.equals("INS")){
            btn_Accion.setText("Insertar");
        }else if(mode.equals("UPD")){
            Libros libros = (Libros) dao.getByLibrosID(LibrosID);
            txt_Titulo.setText(libros.getTitulo());
            txt_Fecha.setText(String.valueOf(libros.getFechaPublicacion()));
            txt_CategoriaID.setText(String.valueOf(libros.getCategoriaID()));
            txt_Edicion.setText(libros.getEdicion());
            
            btn_Accion.setText("Actualizar");
            
        }else if(mode.equals("DLT")){
            Libros libros = (Libros) dao.getByLibrosID(LibrosID);
            txt_Titulo.setText(libros.getTitulo());
            txt_Titulo.setEnabled(false);
            txt_Fecha.setText(String.valueOf(libros.getFechaPublicacion()));
            txt_Fecha.setEnabled(false);
            txt_CategoriaID.setText(String.valueOf(libros.getCategoriaID()));
            txt_CategoriaID.setEnabled(false);
            txt_Edicion.setText(libros.getEdicion());
            txt_Edicion.setEnabled(false);
            btn_Accion.setText("Eliminar");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_LibrosID = new javax.swing.JTextField();
        txt_Titulo = new javax.swing.JTextField();
        jLabelLibrosID = new javax.swing.JLabel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelFecha = new javax.swing.JLabel();
        txt_Fecha = new javax.swing.JTextField();
        jLabelCategoriaID = new javax.swing.JLabel();
        txt_CategoriaID = new javax.swing.JTextField();
        jLabelEdicion = new javax.swing.JLabel();
        txt_Edicion = new javax.swing.JTextField();
        btn_Accion = new javax.swing.JButton();
        btn_Salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txt_LibrosID.setEnabled(false);
        txt_LibrosID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_LibrosIDActionPerformed(evt);
            }
        });

        jLabelLibrosID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelLibrosID.setText("LibrosID");

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTitulo.setText("Titulo");

        jLabelFecha.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelFecha.setText("FechaPublicación");

        jLabelCategoriaID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelCategoriaID.setText("CategoriaID");

        jLabelEdicion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelEdicion.setText("Edición");

        btn_Accion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Accion.setText("Guardar");
        btn_Accion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AccionActionPerformed(evt);
            }
        });

        btn_Salir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Salir.setText("Salir");
        btn_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelEdicion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelLibrosID)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_Edicion, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_LibrosID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelFecha)
                                    .addComponent(jLabelTitulo))
                                .addGap(29, 29, 29))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelCategoriaID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(59, 59, 59)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_CategoriaID, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_Accion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_Salir)
                        .addGap(90, 90, 90))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_LibrosID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelLibrosID))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTitulo)
                    .addComponent(txt_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFecha))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCategoriaID)
                    .addComponent(txt_CategoriaID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEdicion)
                    .addComponent(txt_Edicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Accion)
                    .addComponent(btn_Salir))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_LibrosIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_LibrosIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_LibrosIDActionPerformed

    private void btn_AccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AccionActionPerformed
        // TODO add your handling code here:
        if(mode.equals("INS")){
            Libros libros = new Libros();
            libros.setTitulo(txt_Titulo.getText());
            try {
            java.sql.Date fecha = java.sql.Date.valueOf(txt_Fecha.getText()); // debe estar en formato yyyy-MM-dd
            libros.setFechaPublicacion(fecha);
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, "La fecha debe tener el formato yyyy-MM-dd", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            libros.setCategoriaID(Integer.parseInt(txt_CategoriaID.getText()));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El ID de categoría debe ser un número válido.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
            libros.setEdicion(txt_Edicion.getText()); 
            dao.insert(libros);
            
            parent.refrescarInfo();
            
            this.dispose();
        }
        
        if(mode.equals("UPD")){
            Libros libros = new Libros();
            libros.setTitulo(txt_Titulo.getText());
            libros.setLibrosID(LibrosID);
            try {
            java.sql.Date fecha = java.sql.Date.valueOf(txt_Fecha.getText()); // debe estar en formato yyyy-MM-dd
            libros.setFechaPublicacion(fecha);
            libros.setLibrosID(LibrosID);
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, "La fecha debe tener el formato yyyy-MM-dd", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            libros.setCategoriaID(Integer.parseInt(txt_CategoriaID.getText()));
            libros.setLibrosID(LibrosID);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El ID de categoría debe ser un número válido.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
            libros.setEdicion(txt_Edicion.getText());
            libros.setLibrosID(LibrosID);
            dao.update(libros);
            
            parent.refrescarInfo();
            
            this.dispose();
        }
        
        if(mode.equals("DLT")){
            dao.delete(LibrosID);
            
            parent.refrescarInfo();
            
            this.dispose();
        }
        
        
    }//GEN-LAST:event_btn_AccionActionPerformed

    private void btn_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_SalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                FormularioLibros dialog = new FormularioLibros(new ListadoLibros(), true, "INS", 0);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Accion;
    private javax.swing.JButton btn_Salir;
    private javax.swing.JLabel jLabelCategoriaID;
    private javax.swing.JLabel jLabelEdicion;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelLibrosID;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JTextField txt_CategoriaID;
    private javax.swing.JTextField txt_Edicion;
    private javax.swing.JTextField txt_Fecha;
    private javax.swing.JTextField txt_LibrosID;
    private javax.swing.JTextField txt_Titulo;
    // End of variables declaration//GEN-END:variables
}
