/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View;

import Controller.TipoUsuarioDAO;
import Model.TipoUsuario;
/**
 *
 * @author Carlos
 */
public class FormularioTipoUsuario extends javax.swing.JDialog {
    
    private String mode;
    private int TipoUsuarioID;
    private TipoUsuarioDAO dao;
    private ListadoTipoUsuario parent;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormularioTipoUsuario.class.getName());

    /**
     * Creates new form FormularioTipoUsuario
     */
    public FormularioTipoUsuario(ListadoTipoUsuario pParent, boolean modal, String pMode, int pTipoUsuarioID) {
        super(pParent, modal);
        this.parent = pParent;
        initComponents();
        setLocationRelativeTo(null);
        
         dao = new TipoUsuarioDAO();
        this.mode = pMode;
        this.TipoUsuarioID = pTipoUsuarioID;
        txt_TipoUsuarioID.setText(String.valueOf(pTipoUsuarioID));
        if(mode.equals("INS")){
            bnt_accion.setText("Insertar");
        }else if(mode.equals("UPD")){
            TipoUsuario tipousuario = (TipoUsuario) dao.getByTipoUsuarioID(TipoUsuarioID);
            txt_DescripcionUsuario.setText(tipousuario.getDescripcionUsuario());

            bnt_accion.setText("Actualizar");
            
        }else if(mode.equals("DLT")){
            TipoUsuario tipousuario = (TipoUsuario) dao.getByTipoUsuarioID(TipoUsuarioID);
            txt_DescripcionUsuario.setText(tipousuario.getDescripcionUsuario());
            txt_DescripcionUsuario.setEnabled(false);
            bnt_accion.setText("Eliminar");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_TipoUsuarioID = new javax.swing.JTextField();
        txt_DescripcionUsuario = new javax.swing.JTextField();
        bnt_accion = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tipo Usuario");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("TipoUsuarioID");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("DescripcionUsuario");

        txt_TipoUsuarioID.setEnabled(false);

        bnt_accion.setBackground(new java.awt.Color(0, 153, 102));
        bnt_accion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bnt_accion.setForeground(new java.awt.Color(204, 204, 204));
        bnt_accion.setText("Guardar");
        bnt_accion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt_accionActionPerformed(evt);
            }
        });

        btn_salir.setBackground(new java.awt.Color(204, 51, 0));
        btn_salir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_salir.setText("Salir");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_DescripcionUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_TipoUsuarioID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bnt_accion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_salir)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel1)
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_DescripcionUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(txt_TipoUsuarioID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bnt_accion)
                    .addComponent(btn_salir))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bnt_accionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt_accionActionPerformed
        // TODO add your handling code here:
        
        if(mode.equals("INS")){
            TipoUsuario tipousuario = new TipoUsuario();
            tipousuario.setDescripcionUsuario(txt_DescripcionUsuario.getText());
            dao.insert(tipousuario);
            
            parent.refrescarInfo();
            
            this.dispose();
        }
        
        if(mode.equals("UPD")){
            TipoUsuario tipousuario = new TipoUsuario();
            tipousuario.setDescripcionUsuario(txt_DescripcionUsuario.getText());
            tipousuario.setTipoUsuarioID(TipoUsuarioID);
            dao.update(tipousuario);
            
            parent.refrescarInfo();
            
            this.dispose();
        }
        
        if(mode.equals("DLT")){
            dao.delete(TipoUsuarioID);
            
            parent.refrescarInfo();
            
            this.dispose();
        }
        
    }//GEN-LAST:event_bnt_accionActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
    }//GEN-LAST:event_btn_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog 
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                FormularioTipoUsuario dialog = new FormularioTipoUsuario(new ListadoTipoUsuario(), true, "INS", 0);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnt_accion;
    private javax.swing.JButton btn_salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txt_DescripcionUsuario;
    private javax.swing.JTextField txt_TipoUsuarioID;
    // End of variables declaration//GEN-END:variables
}
