/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View;
import Controller.DevolucionesDAO;
import Model.Devoluciones;
import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class FormularioDevoluciones extends javax.swing.JDialog {
    private String mode;
    private int DevolucionID;
    private DevolucionesDAO dao;
    private ListadoDevoluciones parent;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormularioDevoluciones.class.getName());

    /**
     * Creates new form FormularioDevoluciones
     */
    public FormularioDevoluciones(ListadoDevoluciones pParent, boolean modal, String pMode, int pDevolucionID) {
        super(pParent, modal);
        this.parent = pParent;
        initComponents();
        
        initComponents();
        setLocationRelativeTo(null);
        
        dao = new DevolucionesDAO();
        this.mode = pMode;
        this.DevolucionID = pDevolucionID;
        txt_DevolucionID.setText(String.valueOf(DevolucionID));
        if(mode.equals("INS")){
            btn_Accion.setText("Insertar");
        }else if(mode.equals("UPD")){
            Devoluciones devoluciones = (Devoluciones) dao.getByDevolucionID(DevolucionID);
            txt_EjemplarID.setText(String.valueOf(devoluciones.getEjemplarID()));
            txt_PrestamoID.setText(String.valueOf(devoluciones.getPrestamoID()));
            txt_FechaDevolucion.setText(String.valueOf(devoluciones.getFechaDevolucion()));
            txt_Comentario.setText(devoluciones.getComentario());
            txt_EmpleadoID.setText(String.valueOf(devoluciones.getEmpleadoID()));
            
            
            btn_Accion.setText("Actualizar");
            
        }else if(mode.equals("DLT")){
            Devoluciones devoluciones = (Devoluciones) dao.getByDevolucionID(DevolucionID);
            txt_EjemplarID.setText(String.valueOf(devoluciones.getEjemplarID()));
            txt_EjemplarID.setEnabled(false);
            txt_PrestamoID.setText(String.valueOf(devoluciones.getPrestamoID()));
            txt_PrestamoID.setEnabled(false);
            txt_FechaDevolucion.setText(String.valueOf(devoluciones.getFechaDevolucion()));
            txt_FechaDevolucion.setEnabled(false);
            txt_Comentario.setText(devoluciones.getComentario());
            txt_Comentario.setEnabled(false);
            txt_EmpleadoID.setText(String.valueOf(devoluciones.getEmpleadoID()));
            txt_EmpleadoID.setEnabled(false);
            btn_Accion.setText("Eliminar");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelDevolucionID = new javax.swing.JLabel();
        jLabelEjemplarID = new javax.swing.JLabel();
        jLabelPrestamoID = new javax.swing.JLabel();
        jLabelFechaDevolucion = new javax.swing.JLabel();
        jLabelComentario = new javax.swing.JLabel();
        jLabelEmpleadoID = new javax.swing.JLabel();
        txt_DevolucionID = new javax.swing.JTextField();
        txt_EjemplarID = new javax.swing.JTextField();
        txt_PrestamoID = new javax.swing.JTextField();
        txt_FechaDevolucion = new javax.swing.JTextField();
        txt_Comentario = new javax.swing.JTextField();
        txt_EmpleadoID = new javax.swing.JTextField();
        btn_Accion = new javax.swing.JButton();
        btn_Salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelDevolucionID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelDevolucionID.setText("DevolucionID");

        jLabelEjemplarID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelEjemplarID.setText("EjemplarID");

        jLabelPrestamoID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelPrestamoID.setText("PrestamoID");

        jLabelFechaDevolucion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelFechaDevolucion.setText("FechaDevolucion");

        jLabelComentario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelComentario.setText("Comentario");

        jLabelEmpleadoID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelEmpleadoID.setText("EmpleadoID");

        txt_DevolucionID.setEnabled(false);

        btn_Accion.setBackground(new java.awt.Color(0, 204, 0));
        btn_Accion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Accion.setForeground(new java.awt.Color(255, 255, 255));
        btn_Accion.setText("Guardar");
        btn_Accion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AccionActionPerformed(evt);
            }
        });

        btn_Salir.setBackground(new java.awt.Color(204, 204, 204));
        btn_Salir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Salir.setForeground(new java.awt.Color(255, 255, 255));
        btn_Salir.setText("Salir");
        btn_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDevolucionID)
                    .addComponent(jLabelEjemplarID)
                    .addComponent(jLabelPrestamoID)
                    .addComponent(jLabelFechaDevolucion)
                    .addComponent(jLabelComentario)
                    .addComponent(jLabelEmpleadoID)
                    .addComponent(btn_Accion))
                .addGap(124, 124, 124)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Salir)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txt_EmpleadoID, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_PrestamoID, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_EjemplarID, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_DevolucionID, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_FechaDevolucion, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                        .addComponent(txt_Comentario)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDevolucionID)
                    .addComponent(txt_DevolucionID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEjemplarID)
                    .addComponent(txt_EjemplarID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPrestamoID)
                    .addComponent(txt_PrestamoID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFechaDevolucion)
                    .addComponent(txt_FechaDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelComentario)
                    .addComponent(txt_Comentario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabelEmpleadoID))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txt_EmpleadoID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Accion)
                    .addComponent(btn_Salir))
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_AccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AccionActionPerformed
        // TODO add your handling code here:
        
        if(mode.equals("INS")){
            Devoluciones devoluciones = new Devoluciones();
            try {
            devoluciones.setEjemplarID(Integer.parseInt(txt_EjemplarID.getText()));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El ID de Ejemplares debe ser un número válido.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
            
            try {
            devoluciones.setPrestamoID(Integer.parseInt(txt_PrestamoID.getText()));
               } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El ID de Pestamos debe ser un número válido.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } 
            
            try {
            java.sql.Date fecha = java.sql.Date.valueOf(txt_FechaDevolucion.getText()); // debe estar en formato yyyy-MM-dd
            devoluciones.setFechaDevolucion(fecha);
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, "La fecha debe tener el formato yyyy-MM-dd", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

            devoluciones.setComentario(txt_Comentario.getText()); 
            
        try {
            devoluciones.setEmpleadoID(Integer.parseInt(txt_EmpleadoID.getText()));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El ID de Empleado debe ser un número válido.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
            
            dao.insert(devoluciones);
            
            parent.refrescarInfo();
            
            this.dispose();
        }
        
        if(mode.equals("UPD")){
            Devoluciones devoluciones = new Devoluciones();
            
             try {
            devoluciones.setEjemplarID(Integer.parseInt(txt_EjemplarID.getText()));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El ID de Ejemplares debe ser un número válido.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
            
            try {
            devoluciones.setPrestamoID(Integer.parseInt(txt_PrestamoID.getText()));
               } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El ID de Pestamos debe ser un número válido.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } 
            
            try {
            java.sql.Date fecha = java.sql.Date.valueOf(txt_FechaDevolucion.getText()); // debe estar en formato yyyy-MM-dd
            devoluciones.setFechaDevolucion(fecha);
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, "La fecha debe tener el formato yyyy-MM-dd", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

            devoluciones.setComentario(txt_Comentario.getText()); 
            
        try {
            devoluciones.setEmpleadoID(Integer.parseInt(txt_EmpleadoID.getText()));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El ID de Empleado debe ser un número válido.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
            dao.update(devoluciones);
            
            parent.refrescarInfo();
            
            this.dispose();
        }
        
        if(mode.equals("DLT")){
            dao.delete(DevolucionID);
            
            parent.refrescarInfo();
            
            this.dispose();
        }
        
        
    }//GEN-LAST:event_btn_AccionActionPerformed

    private void btn_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_SalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                FormularioDevoluciones dialog = new FormularioDevoluciones(new ListadoDevoluciones(), true, "INS", 0);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Accion;
    private javax.swing.JButton btn_Salir;
    private javax.swing.JLabel jLabelComentario;
    private javax.swing.JLabel jLabelDevolucionID;
    private javax.swing.JLabel jLabelEjemplarID;
    private javax.swing.JLabel jLabelEmpleadoID;
    private javax.swing.JLabel jLabelFechaDevolucion;
    private javax.swing.JLabel jLabelPrestamoID;
    private javax.swing.JTextField txt_Comentario;
    private javax.swing.JTextField txt_DevolucionID;
    private javax.swing.JTextField txt_EjemplarID;
    private javax.swing.JTextField txt_EmpleadoID;
    private javax.swing.JTextField txt_FechaDevolucion;
    private javax.swing.JTextField txt_PrestamoID;
    // End of variables declaration//GEN-END:variables
}
