/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View;

import Controller.RolDAO;
import Model.Rol;

/**
 *
 * @author Dell
 */
public class FormularioRol extends javax.swing.JDialog {
    
    private String mode;
    private int RolID;
    private RolDAO dao;
    private ListaRol parent;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormularioRol.class.getName());

    /**
     * Creates new form FormularioRol
     */
    public FormularioRol(ListaRol pParent, boolean modal, String pMode, int pRolID) {
        super(pParent, modal);
        this.parent = pParent;
        initComponents();
        setLocationRelativeTo(null);
        
         dao = new RolDAO();
        this.mode = pMode;
        this.RolID = pRolID;
        txt_RolID.setText(String.valueOf(pRolID));
        if(mode.equals("INS")){
            btn_Accion.setText("Insertar");
        }else if(mode.equals("UPD")){
            Rol rol = (Rol) dao.getByRolID(RolID);
            txt_RolDescripcion.setText(rol.getRolDescripcion());

            btn_Accion.setText("Actualizar");
            
        }else if(mode.equals("DLT")){
            Rol rol = (Rol) dao.getByRolID(RolID);
            txt_RolDescripcion.setText(rol.getRolDescripcion());
            txt_RolDescripcion.setEnabled(false);
            btn_Accion.setText("Eliminar");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelRolID = new javax.swing.JLabel();
        jLabelRolDescripcion = new javax.swing.JLabel();
        txt_RolID = new javax.swing.JTextField();
        txt_RolDescripcion = new javax.swing.JTextField();
        btn_Accion = new javax.swing.JButton();
        btn_Salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelRolID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelRolID.setText("RolID");

        jLabelRolDescripcion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelRolDescripcion.setText("RolDescripcion");

        txt_RolID.setEnabled(false);

        btn_Accion.setBackground(new java.awt.Color(0, 102, 102));
        btn_Accion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Accion.setForeground(new java.awt.Color(255, 255, 255));
        btn_Accion.setText("Guardar");
        btn_Accion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AccionActionPerformed(evt);
            }
        });

        btn_Salir.setBackground(new java.awt.Color(204, 204, 204));
        btn_Salir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_Salir.setForeground(new java.awt.Color(51, 0, 102));
        btn_Salir.setText("Salir");
        btn_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelRolID)
                    .addComponent(jLabelRolDescripcion)
                    .addComponent(btn_Accion, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_RolID, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_RolDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(btn_Salir)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRolID)
                    .addComponent(txt_RolID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRolDescripcion)
                    .addComponent(txt_RolDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Accion)
                    .addComponent(btn_Salir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(89, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_AccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AccionActionPerformed
        // TODO add your handling code here:
        
        if(mode.equals("INS")){
            Rol rol = new Rol();
            rol.setRolDescripcion(txt_RolDescripcion.getText());
            dao.insert(rol);
            
            parent.refrescarInfo();
            
            this.dispose();
        }
        
        if(mode.equals("UPD")){
            Rol rol = new Rol();
            rol.setRolDescripcion(txt_RolDescripcion.getText());
            rol.setRolID(RolID);
            dao.update(rol);
            
            parent.refrescarInfo();
            
            this.dispose();
        }
        
        if(mode.equals("DLT")){
            dao.delete(RolID);
            
            parent.refrescarInfo();
            
            this.dispose();
        }
        
    }//GEN-LAST:event_btn_AccionActionPerformed

    private void btn_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SalirActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
    }//GEN-LAST:event_btn_SalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                FormularioRol dialog = new FormularioRol(new ListaRol(), true, "INS", 0);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Accion;
    private javax.swing.JButton btn_Salir;
    private javax.swing.JLabel jLabelRolDescripcion;
    private javax.swing.JLabel jLabelRolID;
    private javax.swing.JTextField txt_RolDescripcion;
    private javax.swing.JTextField txt_RolID;
    // End of variables declaration//GEN-END:variables
}
