/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View;

import Controller.EjemplaresDAO;
import Model.Ejemplares;
import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class FormularioEjemplares extends javax.swing.JDialog {
    
     private String mode;
    private int EjemplarID;
    private EjemplaresDAO dao;
    private ListadoEjemplares parent;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormularioEjemplares.class.getName());

    /**
     * Creates new form FormularioEjemplares
     */
    public FormularioEjemplares(ListadoEjemplares pParent, boolean modal, String pMode, int pEjemplarID) {
        super(pParent, modal);
        this.parent = pParent;
        initComponents();
        
        setLocationRelativeTo(null);
                
        dao = new EjemplaresDAO();
        this.mode = pMode;
        this.EjemplarID = pEjemplarID;
        txt_EjemplarID.setText(String.valueOf(EjemplarID));
        if(mode.equals("INS")){
            btn_Accion.setText("Insertar");
        }else if(mode.equals("UPD")){
            Ejemplares ejemplares = (Ejemplares) dao.getByEjemplarID(EjemplarID);
            txt_LibroID.setText(String.valueOf(ejemplares.getLibroID()));
            txt_FechaIngreso.setText(String.valueOf(ejemplares.getFechaIngreso()));
            txt_Estado.setText(String.valueOf(ejemplares.getEstado()));
            
            
            btn_Accion.setText("Actualizar");
            
        }else if(mode.equals("DLT")){
            Ejemplares ejemplares = (Ejemplares) dao.getByEjemplarID(EjemplarID);
            txt_LibroID.setText(String.valueOf(ejemplares.getLibroID()));
            txt_LibroID.setEnabled(false);
            txt_FechaIngreso.setText(String.valueOf(ejemplares.getFechaIngreso()));
            txt_FechaIngreso.setEnabled(false);
            txt_Estado.setText(String.valueOf(ejemplares.getEstado()));
            txt_Estado.setEnabled(false);
            btn_Accion.setText("Eliminar");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelEjemplarID = new javax.swing.JLabel();
        jLabelLibroID = new javax.swing.JLabel();
        jLabelFechaIngreso = new javax.swing.JLabel();
        jLabelEstado = new javax.swing.JLabel();
        txt_EjemplarID = new javax.swing.JTextField();
        txt_LibroID = new javax.swing.JTextField();
        txt_FechaIngreso = new javax.swing.JTextField();
        txt_Estado = new javax.swing.JTextField();
        btn_Accion = new javax.swing.JButton();
        btn_Salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelEjemplarID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelEjemplarID.setText("EjemplarID");

        jLabelLibroID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelLibroID.setText("LibroID");

        jLabelFechaIngreso.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelFechaIngreso.setText("FechaIngreso");

        jLabelEstado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelEstado.setText("Estado");

        txt_EjemplarID.setEnabled(false);

        btn_Accion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Accion.setText("Guardar");
        btn_Accion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AccionActionPerformed(evt);
            }
        });

        btn_Salir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Salir.setText("Salir");
        btn_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelEjemplarID)
                            .addComponent(jLabelLibroID)
                            .addComponent(jLabelFechaIngreso)
                            .addComponent(jLabelEstado))
                        .addGap(122, 122, 122)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_FechaIngreso, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                            .addComponent(txt_LibroID)
                            .addComponent(txt_EjemplarID)
                            .addComponent(txt_Estado)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(btn_Accion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_Salir)))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEjemplarID)
                    .addComponent(txt_EjemplarID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLibroID)
                    .addComponent(txt_LibroID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFechaIngreso)
                    .addComponent(txt_FechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEstado)
                    .addComponent(txt_Estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Accion)
                    .addComponent(btn_Salir))
                .addGap(56, 56, 56))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_AccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AccionActionPerformed
        // TODO add your handling code here:
        if(mode.equals("INS")){
            Ejemplares ejemplares = new Ejemplares();
            try {
            ejemplares.setLibroID(Integer.parseInt(txt_LibroID.getText()));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El ID de Libros debe ser un número válido.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
            
            
            try {
            java.sql.Date fecha = java.sql.Date.valueOf(txt_FechaIngreso.getText()); // debe estar en formato yyyy-MM-dd
            ejemplares.setFechaIngreso(fecha);
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, "La fecha debe tener el formato yyyy-MM-dd", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

            
        try {
            ejemplares.setEstado(Integer.parseInt(txt_Estado.getText()));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El ID de Estado debe ser un número válido.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
            
            dao.insert(ejemplares);
            
            parent.refrescarInfo();
            
            this.dispose();
        }
        
        if(mode.equals("UPD")){
             Ejemplares ejemplares = new Ejemplares();
            try {
            ejemplares.setLibroID(Integer.parseInt(txt_LibroID.getText()));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El ID de Libros debe ser un número válido.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
            
            
            try {
            java.sql.Date fecha = java.sql.Date.valueOf(txt_FechaIngreso.getText()); // debe estar en formato yyyy-MM-dd
            ejemplares.setFechaIngreso(fecha);
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, "La fecha debe tener el formato yyyy-MM-dd", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

            
        try {
            ejemplares.setEstado(Integer.parseInt(txt_Estado.getText()));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El ID de Estado debe ser un número válido.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        
        }
            dao.update(ejemplares);
            
            parent.refrescarInfo();
            
            this.dispose();
        }
        
        if(mode.equals("DLT")){
            dao.delete(EjemplarID);
            
            parent.refrescarInfo();
            
            this.dispose();
        }
    }//GEN-LAST:event_btn_AccionActionPerformed

    private void btn_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_SalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                FormularioEjemplares dialog = new FormularioEjemplares(new ListadoEjemplares(), true, "INS", 0);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Accion;
    private javax.swing.JButton btn_Salir;
    private javax.swing.JLabel jLabelEjemplarID;
    private javax.swing.JLabel jLabelEstado;
    private javax.swing.JLabel jLabelFechaIngreso;
    private javax.swing.JLabel jLabelLibroID;
    private javax.swing.JTextField txt_EjemplarID;
    private javax.swing.JTextField txt_Estado;
    private javax.swing.JTextField txt_FechaIngreso;
    private javax.swing.JTextField txt_LibroID;
    // End of variables declaration//GEN-END:variables
}
