/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View;

import Controller.AutoresDAO;
import Model.Autores;

/**
 *
 * @author Dell
 */
public class FormularioAutores extends javax.swing.JDialog {
    
    private String mode;
    private int AutorID;
    private AutoresDAO dao;
    private ListadoAutores parent;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormularioAutores.class.getName());

    /**
     * Creates new form FormularioAutores
     */
    public FormularioAutores(ListadoAutores pParent, boolean modal, String pMode, int pAutorID) {
        super(pParent, modal);
        this.parent = pParent;
        initComponents();
        setLocationRelativeTo(null);
        
         dao = new AutoresDAO();
        this.mode = pMode;
        this.AutorID = pAutorID;
        txt_AutorID.setText(String.valueOf(pAutorID));
        if(mode.equals("INS")){
            btn_Accion.setText("Insertar");
        }else if(mode.equals("UPD")){
            Autores autores = (Autores) dao.getByAutorID(AutorID);
            txt_NombreAutor.setText(autores.getNombreAutor());
            txt_ApellidoAutor.setText(autores.getApellidoAutor());
            
            btn_Accion.setText("Actualizar");
            
        }else if(mode.equals("DLT")){
            Autores autores = (Autores) dao.getByAutorID(AutorID);
            txt_NombreAutor.setText(autores.getNombreAutor());
            txt_NombreAutor.setEnabled(false);
            txt_ApellidoAutor.setText(autores.getApellidoAutor());
            txt_ApellidoAutor.setEnabled(false);
            
            btn_Accion.setText("Eliminar");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelAutorID = new javax.swing.JLabel();
        jLabelNombreAutor = new javax.swing.JLabel();
        jLabelApellidoAutor = new javax.swing.JLabel();
        txt_AutorID = new javax.swing.JTextField();
        txt_NombreAutor = new javax.swing.JTextField();
        txt_ApellidoAutor = new javax.swing.JTextField();
        btn_Accion = new javax.swing.JButton();
        btn_Salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Autores");
        setBackground(new java.awt.Color(204, 204, 204));

        jLabelAutorID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelAutorID.setText("AutorID");

        jLabelNombreAutor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelNombreAutor.setText("NombreAutor");

        jLabelApellidoAutor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelApellidoAutor.setText("ApellidoAutor");

        txt_AutorID.setEnabled(false);

        btn_Accion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Accion.setText("Guardar");
        btn_Accion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AccionActionPerformed(evt);
            }
        });

        btn_Salir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Salir.setText("Salir");
        btn_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelApellidoAutor)
                    .addComponent(jLabelNombreAutor)
                    .addComponent(jLabelAutorID))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_NombreAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_ApellidoAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_AutorID, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(btn_Accion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_Salir)
                .addGap(74, 74, 74))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAutorID)
                    .addComponent(txt_AutorID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNombreAutor)
                            .addComponent(txt_NombreAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelApellidoAutor)
                            .addComponent(txt_ApellidoAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_Salir)
                            .addComponent(btn_Accion))
                        .addGap(66, 66, 66))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SalirActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
    }//GEN-LAST:event_btn_SalirActionPerformed

    private void btn_AccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AccionActionPerformed
        // TODO add your handling code here:
        
        if(mode.equals("INS")){
            Autores autores= new Autores ();
            autores.setNombreAutor(txt_NombreAutor.getText());
            autores.setApellidoAutor(txt_ApellidoAutor.getText());
            dao.insert(autores);
            
            parent.refrescarInfo();
            
            this.dispose();
        }
        
        if(mode.equals("UPD")){
            Autores autores= new Autores ();
            autores.setNombreAutor(txt_NombreAutor.getText());
            autores.setAutorID(AutorID);
            autores.setApellidoAutor(txt_ApellidoAutor.getText());
            autores.setAutorID(AutorID);
            
            dao.update(autores);
            
            parent.refrescarInfo();
            
            this.dispose();
        }
        
        if(mode.equals("DLT")){
            dao.delete(AutorID);
            
            parent.refrescarInfo();
            
            this.dispose();
        }
    }//GEN-LAST:event_btn_AccionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                FormularioAutores dialog = new FormularioAutores(new ListadoAutores(), true, "INS", 0);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Accion;
    private javax.swing.JButton btn_Salir;
    private javax.swing.JLabel jLabelApellidoAutor;
    private javax.swing.JLabel jLabelAutorID;
    private javax.swing.JLabel jLabelNombreAutor;
    private javax.swing.JTextField txt_ApellidoAutor;
    private javax.swing.JTextField txt_AutorID;
    private javax.swing.JTextField txt_NombreAutor;
    // End of variables declaration//GEN-END:variables
}
