/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View;
import Controller.UsuariosDAO;
import Model.Usuarios;
import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class FormularioUsuarios extends javax.swing.JDialog {
    
    private String mode;
    private int UsuarioID;
    private UsuariosDAO dao;
    private ListadoUsuarios parent;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormularioUsuarios.class.getName());

    /**
     * Creates new form FormularioUsuarios
     */
    public FormularioUsuarios(ListadoUsuarios pParent, boolean modal, String pMode, int pUsuarioID) {
        super(pParent, modal);
        this.parent = pParent;
        initComponents();
        
        setLocationRelativeTo(null);
        
        dao = new UsuariosDAO();
        this.mode = pMode;
        this.UsuarioID = pUsuarioID;
        txt_UsuarioID.setText(String.valueOf(UsuarioID));
        if(mode.equals("INS")){
            btn_Accion.setText("Insertar");
        }else if(mode.equals("UPD")){
            Usuarios usuarios = (Usuarios) dao.getByUsuarioID(UsuarioID);
            txt_UsuarioID.setText(String.valueOf(usuarios.getUsuarioID()));
            txt_Correo.setText(usuarios.getCorreo());
            txt_Telefono.setText(usuarios.getTelefono());
            txt_Direccion.setText(usuarios.getDireccion());
            txt_Nombre.setText(usuarios.getNombre());
            txt_Apellido.setText(usuarios.getApellido());
            //jCBoxTipoUsuarioID.setText(String.valueOf(usuarios.getTipoUsuarioID()));//
            txt_Status.setText(String.valueOf(usuarios.getStatus()));
            //txt_Contraseña.setText(usuarios.getContraseña());//
            
            
            btn_Accion.setText("Actualizar");
            
        }else if(mode.equals("DLT")){
            Usuarios usuarios = (Usuarios) dao.getByUsuarioID(UsuarioID);
            txt_UsuarioID.setText(String.valueOf(usuarios.getUsuarioID()));
            txt_UsuarioID.setEnabled(false);
            txt_Correo.setText(usuarios.getCorreo());
            txt_Correo.setEnabled(false);
            txt_Telefono.setText(usuarios.getTelefono());
            txt_Telefono.setEnabled(false);
            txt_Direccion.setText(usuarios.getDireccion());
            txt_Direccion.setEnabled(false);
            txt_Nombre.setText(usuarios.getNombre());
            txt_Nombre.setEnabled(false);
            txt_Apellido.setText(usuarios.getApellido());
            txt_Apellido.setEnabled(false);
            //jCBoxTipoUsuarioID.setText(String.valueOf(usuarios.getTipoUsuarioID()));//
            //jCBoxTipoUsuarioID.setEnabled(false);//
            txt_Status.setText(String.valueOf(usuarios.getStatus()));
            txt_Status.setEnabled(false);
            //txt_Contraseña.setText(usuarios.getContraseña());
            //txt_Contraseña.setEnabled(false);
            
            btn_Accion.setText("Eliminar");
        }
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelUsuarioID = new javax.swing.JLabel();
        jLabelCorreo = new javax.swing.JLabel();
        jLabelTelefono = new javax.swing.JLabel();
        jLabelDireccion = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelApellido = new javax.swing.JLabel();
        jblStatus = new javax.swing.JLabel();
        txt_UsuarioID = new javax.swing.JTextField();
        txt_Correo = new javax.swing.JTextField();
        txt_Telefono = new javax.swing.JTextField();
        txt_Direccion = new javax.swing.JTextField();
        txt_Nombre = new javax.swing.JTextField();
        txt_Apellido = new javax.swing.JTextField();
        txt_Status = new javax.swing.JTextField();
        btn_Accion = new javax.swing.JButton();
        btn_Salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro de Usuarios");

        jLabelUsuarioID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelUsuarioID.setText("UsuarioID");

        jLabelCorreo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelCorreo.setText("Correo");

        jLabelTelefono.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTelefono.setText("Telefono");

        jLabelDireccion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelDireccion.setText("Direccion");

        jLabelNombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelNombre.setText("Nombre");

        jLabelApellido.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelApellido.setText("Apellido");

        jblStatus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jblStatus.setText("Status");

        txt_UsuarioID.setEnabled(false);

        btn_Accion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Accion.setText("Guardar");
        btn_Accion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AccionActionPerformed(evt);
            }
        });

        btn_Salir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Salir.setText("Salir");
        btn_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabelUsuarioID)
                                .addGap(194, 194, 194)
                                .addComponent(jLabelCorreo))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jLabelDireccion)
                                .addGap(147, 147, 147)
                                .addComponent(jLabelNombre)))
                        .addGap(0, 34, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(txt_UsuarioID, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(108, 108, 108))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_Status, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_Nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                            .addComponent(txt_Correo))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabelTelefono)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabelApellido)
                        .addGap(54, 54, 54))
                    .addComponent(txt_Telefono, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                    .addComponent(txt_Apellido))
                .addGap(45, 45, 45))
            .addGroup(layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(btn_Accion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_Salir)
                .addGap(183, 183, 183))
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jblStatus)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUsuarioID)
                    .addComponent(jLabelCorreo)
                    .addComponent(jLabelTelefono))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_UsuarioID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelDireccion)
                            .addComponent(jLabelNombre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addComponent(jblStatus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelApellido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)))
                .addComponent(txt_Status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Accion)
                    .addComponent(btn_Salir))
                .addGap(75, 75, 75))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_AccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AccionActionPerformed
        // TODO add your handling code here:
        
        if(mode.equals("INS")){
            Usuarios usuarios = new  Usuarios();
            
            usuarios.setCorreo(txt_Correo.getText()); 
            usuarios.setTelefono(txt_Telefono.getText());
            usuarios.setDireccion(txt_Direccion.getText());
            usuarios.setNombre(txt_Nombre.getText());
            usuarios.setApellido(txt_Apellido.getText());
            
            
           /** try {
            usuarios.setTipoUsuarioID(Integer.parseInt(txt_TipoUsuarioID.getText()));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El ID de Ejemplares debe ser un número válido.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }**/
            
            try {
            usuarios.setStatus(Integer.parseInt(txt_Status.getText()));
               } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El Status de Usuarios debe ser un número válido.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } 
            

            //usuarios.setContraseña(txt_Contraseña.getText());//
            
            
            dao.insert(usuarios);
            
            parent.refrescarInfo();
            
            this.dispose();
        }
        
        if(mode.equals("UPD")){
            Usuarios usuarios = new  Usuarios();
            usuarios.setUsuarioID(UsuarioID); 
            usuarios.setCorreo(txt_Correo.getText()); 
            usuarios.setTelefono(txt_Telefono.getText());
            usuarios.setDireccion(txt_Direccion.getText());
            usuarios.setNombre(txt_Nombre.getText());
            usuarios.setApellido(txt_Apellido.getText());
            
            
           /* try {
            usuarios.setTipoUsuarioID(Integer.parseInt(txt_TipoUsuarioID.getText()));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El ID de Ejemplares debe ser un número válido.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }*/
            
            try {
            usuarios.setStatus(Integer.parseInt(txt_Status.getText()));
               } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El Status de Usuarios debe ser un número válido.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } 
            
            //usuarios.setContraseña(txt_Contraseña.getText());//
            
            dao.update(usuarios);
            
            parent.refrescarInfo();
            
            this.dispose();
        }
        
        if(mode.equals("DLT")){
            dao.delete(UsuarioID);
            
            parent.refrescarInfo();
            
            this.dispose();
        }
        
    }//GEN-LAST:event_btn_AccionActionPerformed

    private void btn_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_SalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                FormularioUsuarios dialog = new FormularioUsuarios(new ListadoUsuarios(), true, "INS", 0);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Accion;
    private javax.swing.JButton btn_Salir;
    private javax.swing.JLabel jLabelApellido;
    private javax.swing.JLabel jLabelCorreo;
    private javax.swing.JLabel jLabelDireccion;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelTelefono;
    private javax.swing.JLabel jLabelUsuarioID;
    private javax.swing.JLabel jblStatus;
    private javax.swing.JTextField txt_Apellido;
    private javax.swing.JTextField txt_Correo;
    private javax.swing.JTextField txt_Direccion;
    private javax.swing.JTextField txt_Nombre;
    private javax.swing.JTextField txt_Status;
    private javax.swing.JTextField txt_Telefono;
    private javax.swing.JTextField txt_UsuarioID;
    // End of variables declaration//GEN-END:variables
}
