/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View;

import Controller.PrestamosDAO;
import Model.Prestamos;
import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class FormularioPrestamos extends javax.swing.JDialog {
    private String mode;
    private int PrestamoID;
    private PrestamosDAO dao;
    private ListadoPrestamos parent;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormularioPrestamos.class.getName());

    /**
     * Creates new form FormularioPrestamos
     */
    public FormularioPrestamos(ListadoPrestamos pParent, boolean modal, String pMode, int pPrestamoID) {
    super(pParent, modal);
    this.parent = pParent;
    initComponents(); // ✅ solo una llamada

    setLocationRelativeTo(null);
    
    dao = new PrestamosDAO();
    this.mode = pMode;
    this.PrestamoID = pPrestamoID;
    txt_PrestamoID.setText(String.valueOf(PrestamoID));

    if(mode.equals("INS")){
        btn_Accion.setText("Insertar");
    }else if(mode.equals("UPD")){
        Prestamos prestamos = (Prestamos) dao.getByLibrosID(PrestamoID);
        txt_UsuarioID.setText(String.valueOf(prestamos.getUsuarioID()));
        txt_EjemplarID.setText(String.valueOf(prestamos.getEjemplarID()));
        txt_FechaEgreso.setText(String.valueOf(prestamos.getFechaEgreso()));
        txt_FechaDevolucionEstimada.setText(String.valueOf(prestamos.getFechaDevolucionEstimada()));
        txt_EmpleadoID.setText(String.valueOf(prestamos.getEmpleadoID()));
        btn_Accion.setText("Actualizar");
    }else if(mode.equals("DLT")){
        Prestamos prestamos = (Prestamos) dao.getByLibrosID(PrestamoID);
        txt_UsuarioID.setText(String.valueOf(prestamos.getUsuarioID()));
        txt_UsuarioID.setEnabled(false);
        txt_EjemplarID.setText(String.valueOf(prestamos.getEjemplarID()));
        txt_EjemplarID.setEnabled(false);
        txt_FechaEgreso.setText(String.valueOf(prestamos.getFechaEgreso()));
        txt_FechaEgreso.setEnabled(false);
        txt_FechaDevolucionEstimada.setText(String.valueOf(prestamos.getFechaDevolucionEstimada()));
        txt_FechaDevolucionEstimada.setEnabled(false);
        txt_EmpleadoID.setText(String.valueOf(prestamos.getEmpleadoID()));
        txt_EmpleadoID.setEnabled(false);
        btn_Accion.setText("Eliminar");
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelPrestamoID = new javax.swing.JLabel();
        jLabelUsuarioID = new javax.swing.JLabel();
        jLabelEjemplarID = new javax.swing.JLabel();
        jLabelFechaEgreso = new javax.swing.JLabel();
        jLabelFechaDevolucionEstimada = new javax.swing.JLabel();
        jlbEmpleadoID = new javax.swing.JLabel();
        txt_PrestamoID = new javax.swing.JTextField();
        txt_UsuarioID = new javax.swing.JTextField();
        txt_EjemplarID = new javax.swing.JTextField();
        txt_FechaEgreso = new javax.swing.JTextField();
        txt_FechaDevolucionEstimada = new javax.swing.JTextField();
        btn_Accion = new javax.swing.JButton();
        btn_Salir = new javax.swing.JButton();
        txt_EmpleadoID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Prestamos");

        jLabelPrestamoID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelPrestamoID.setText("PrestamoID");

        jLabelUsuarioID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelUsuarioID.setText("UsuarioID");

        jLabelEjemplarID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelEjemplarID.setText("EjemplarID");

        jLabelFechaEgreso.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelFechaEgreso.setText("FechaEgreso");

        jLabelFechaDevolucionEstimada.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelFechaDevolucionEstimada.setText("FechaDevolucionEstimada");

        jlbEmpleadoID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlbEmpleadoID.setText("EmpleadoID");

        txt_PrestamoID.setEnabled(false);

        btn_Accion.setBackground(new java.awt.Color(0, 153, 102));
        btn_Accion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Accion.setForeground(new java.awt.Color(204, 255, 255));
        btn_Accion.setText("Guardar");
        btn_Accion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AccionActionPerformed(evt);
            }
        });

        btn_Salir.setBackground(new java.awt.Color(255, 51, 0));
        btn_Salir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Salir.setText("Salir");
        btn_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabelPrestamoID)
                        .addComponent(jLabelUsuarioID, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelEjemplarID, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jLabelFechaEgreso)
                    .addComponent(jLabelFechaDevolucionEstimada)
                    .addComponent(jlbEmpleadoID, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Accion))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txt_PrestamoID, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txt_FechaDevolucionEstimada, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_FechaEgreso, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_EmpleadoID, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_UsuarioID, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txt_EjemplarID, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40))
                            .addComponent(btn_Salir, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabelPrestamoID))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txt_PrestamoID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUsuarioID)
                    .addComponent(txt_UsuarioID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_EjemplarID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEjemplarID))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFechaEgreso)
                    .addComponent(txt_FechaEgreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFechaDevolucionEstimada)
                    .addComponent(txt_FechaDevolucionEstimada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbEmpleadoID)
                    .addComponent(txt_EmpleadoID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Salir)
                    .addComponent(btn_Accion))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_AccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AccionActionPerformed
        // TODO add your handling code here:
        if(mode.equals("INS")){
            Prestamos prestamos = new Prestamos();
            
            try {
            prestamos.setUsuarioID(Integer.parseInt(txt_UsuarioID.getText()));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El ID de Usuarios debe ser un número válido.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } 
            
             try {
            prestamos.setEjemplarID(Integer.parseInt(txt_EjemplarID.getText()));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El ID de Ejemplares debe ser un número válido.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
            
            try {
            java.sql.Date fecha = java.sql.Date.valueOf(txt_FechaEgreso.getText()); // debe estar en formato yyyy-MM-dd
            prestamos.setFechaEgreso(fecha);
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, "La fecha debe tener el formato yyyy-MM-dd", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
            
             try {
            java.sql.Date fecha = java.sql.Date.valueOf(txt_FechaDevolucionEstimada.getText()); // debe estar en formato yyyy-MM-dd
            prestamos.setFechaDevolucionEstimada(fecha);
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, "La fecha debe tener el formato yyyy-MM-dd", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
            
        try {
            prestamos.setEmpleadoID(Integer.parseInt(txt_EmpleadoID.getText()));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El ID de Empleado debe ser un número válido.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
            
            dao.insert(prestamos);
            
            parent.refrescarInfo();
            
            this.dispose();
        }
        
        if(mode.equals("UPD")){
           Prestamos prestamos = new Prestamos();
            
            try {
            prestamos.setUsuarioID(Integer.parseInt(txt_UsuarioID.getText()));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El ID de Usuarios debe ser un número válido.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } 
            
             try {
            prestamos.setEjemplarID(Integer.parseInt(txt_EjemplarID.getText()));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El ID de Ejemplares debe ser un número válido.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
            
            try {
            java.sql.Date fecha = java.sql.Date.valueOf(txt_FechaEgreso.getText()); // debe estar en formato yyyy-MM-dd
            prestamos.setFechaEgreso(fecha);
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, "La fecha debe tener el formato yyyy-MM-dd", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
            
             try {
            java.sql.Date fecha = java.sql.Date.valueOf(txt_FechaDevolucionEstimada.getText()); // debe estar en formato yyyy-MM-dd
            prestamos.setFechaDevolucionEstimada(fecha);
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, "La fecha debe tener el formato yyyy-MM-dd", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
            
        try {
            prestamos.setEmpleadoID(Integer.parseInt(txt_EmpleadoID.getText()));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El ID de Empleado debe ser un número válido.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
            dao.update(prestamos);
            
            parent.refrescarInfo();
            
            this.dispose();
        }
        
        if(mode.equals("DLT")){
            dao.delete(PrestamoID);
            
            parent.refrescarInfo();
            
            this.dispose();
        }
    }//GEN-LAST:event_btn_AccionActionPerformed

    private void btn_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_SalirActionPerformed

    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog 
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                FormularioPrestamos dialog = new FormularioPrestamos(new ListadoPrestamos(), true, "INS", 0);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Accion;
    private javax.swing.JButton btn_Salir;
    private javax.swing.JLabel jLabelEjemplarID;
    private javax.swing.JLabel jLabelFechaDevolucionEstimada;
    private javax.swing.JLabel jLabelFechaEgreso;
    private javax.swing.JLabel jLabelPrestamoID;
    private javax.swing.JLabel jLabelUsuarioID;
    private javax.swing.JLabel jlbEmpleadoID;
    private javax.swing.JTextField txt_EjemplarID;
    private javax.swing.JTextField txt_EmpleadoID;
    private javax.swing.JTextField txt_FechaDevolucionEstimada;
    private javax.swing.JTextField txt_FechaEgreso;
    private javax.swing.JTextField txt_PrestamoID;
    private javax.swing.JTextField txt_UsuarioID;
    // End of variables declaration//GEN-END:variables
}
