/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.EjemplaresDAO;
import Model.Ejemplares;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dell
 */
public class ListadoEjemplares extends javax.swing.JFrame {
    private DefaultTableModel modeloTabla;
    private EjemplaresDAO ejemplaresDAO = new EjemplaresDAO();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ListadoEjemplares.class.getName());

    /**
     * Creates new form ListadoEjemplares
     */
    private Menu menuPadre;
    public ListadoEjemplares(Menu menu) {
        initComponents();
        
         setLocationRelativeTo(null);
        this.menuPadre = menu;
        modeloTabla = (DefaultTableModel) tbl_Ejemplares.getModel();
        cargarDatos();
        
        this.addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosing(java.awt.event.WindowEvent e) {
            if (menuPadre != null) {
                menuPadre.setVisible(true); // Mostrar menú de nuevo
            }
        }
        });
    }
    
    
    private void cargarDatos(){
        modeloTabla.setRowCount(0);
        List<Object>Ejemplares = ejemplaresDAO.getAll();
        for(Object Ejemplares_uncast : Ejemplares){
            Ejemplares ejemplares = (Ejemplares) Ejemplares_uncast;
            modeloTabla.addRow(new Object[]{ejemplares.getEjemplarID(), ejemplares.getLibroID(), ejemplares.getFechaIngreso(), ejemplares.getEstado()});
        }
    }

    
    public void refrescarInfo(){
        cargarDatos();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Ejemplares = new javax.swing.JTable();
        btn_Insertar = new javax.swing.JButton();
        btn_Actualizar = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ejemplares");
        setFont(new java.awt.Font("Agency FB", 0, 10)); // NOI18N

        tbl_Ejemplares.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "EjemplarID", "LibroID", "FechaIngreso", "Estado"
            }
        ));
        jScrollPane1.setViewportView(tbl_Ejemplares);

        btn_Insertar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Insertar.setText("Insertar");
        btn_Insertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_InsertarActionPerformed(evt);
            }
        });

        btn_Actualizar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Actualizar.setText("Actualizar");
        btn_Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ActualizarActionPerformed(evt);
            }
        });

        btn_delete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_delete.setText("Eliminar");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_Insertar)
                        .addGap(104, 104, 104)
                        .addComponent(btn_Actualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_delete)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_Actualizar)
                        .addComponent(btn_delete))
                    .addComponent(btn_Insertar))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_InsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_InsertarActionPerformed
        // TODO add your handling code here:
        FormularioEjemplares formulario = new FormularioEjemplares(this, true, "INS", 0);
        formulario.setVisible(true);
    }//GEN-LAST:event_btn_InsertarActionPerformed

    private void btn_ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ActualizarActionPerformed
        // TODO add your handling code here:
        
         int filaSeleccionada = tbl_Ejemplares.getSelectedRow();
        if(filaSeleccionada == -1){
            JOptionPane.showMessageDialog(this, "Debe Seleccionar una fila", "Error", JOptionPane.ERROR_MESSAGE);
        
        }
        
        int EjemplarID = (int) modeloTabla.getValueAt(filaSeleccionada, 0);
        
        FormularioEjemplares formulario = new FormularioEjemplares(this, true, "UPD", EjemplarID);
        formulario.setVisible(true);
    }//GEN-LAST:event_btn_ActualizarActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
        
        int filaSeleccionada = tbl_Ejemplares.getSelectedRow();
        if(filaSeleccionada == -1){
            JOptionPane.showMessageDialog(this, "Debe Seleccionar una fila", "Error", JOptionPane.ERROR_MESSAGE);
        
        }
        
        int EjemplarID = (int) modeloTabla.getValueAt(filaSeleccionada, 0);
        
        FormularioEjemplares formulario = new FormularioEjemplares(this, true, "DLT", EjemplarID);
        formulario.setVisible(true);
    }//GEN-LAST:event_btn_deleteActionPerformed

    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form 
        java.awt.EventQueue.invokeLater(() -> new ListadoEjemplares().setVisible(true));
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Actualizar;
    private javax.swing.JButton btn_Insertar;
    private javax.swing.JButton btn_delete;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_Ejemplares;
    // End of variables declaration//GEN-END:variables
}
