/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.ReportePrestamosDAO;
import Model.ReportePrestamos;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;

/**
 *
 * @author Dell
 */
public class ListadoReportePrestamos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ListadoReportePrestamos.class.getName());

    /**
     * Creates new form ReportePrestamos
     */
    public ListadoReportePrestamos() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Reporte = new javax.swing.JTable();
        btn_CargarReporte = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Reporte De Prestamos De Libros");

        tbl_Reporte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "prestamoID", "Usuario", "Libro", "FechaEgreso", "fechaDevolucionEstimada", "fechaDevolucion", "Comentario", "EmpleadoPrestamo", "EmpleadoDevolucion"
            }
        ));
        jScrollPane1.setViewportView(tbl_Reporte);

        btn_CargarReporte.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_CargarReporte.setText("Reporte");
        btn_CargarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CargarReporteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_CargarReporte)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_CargarReporte)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_CargarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CargarReporteActionPerformed
        // TODO add your handling code here:
        ReportePrestamosDAO DAO = new ReportePrestamosDAO();
    List<ReportePrestamos> lista = DAO.obtenerReporte();

    DefaultTableModel modelo = new DefaultTableModel();
    modelo.setColumnIdentifiers(new Object[]{
        "ID", "Usuario", "Libro", "Fecha Préstamo", "Fecha Estimada", "Fecha Devolución", "Comentario", "Empleado Préstamo", "Empleado Devolución"
    });

    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");

    for (ReportePrestamos r : lista) {
        String fechaEgreso = (r.getFechaEgreso() != null) ? sdf.format(r.getFechaEgreso()) : "";
        String fechaEstimada = (r.getFechaDevolucionEstimada() != null) ? sdf.format(r.getFechaDevolucionEstimada()) : "";
        String fechaDevolucion = (r.getFechaDevolucion() != null) ? sdf.format(r.getFechaDevolucion()) : "";

        modelo.addRow(new Object[]{
            r.getPrestamoID(),
            r.getUsuario(),
            r.getLibro(),
            fechaEgreso,
            fechaEstimada,
            fechaDevolucion,
            r.getComentario(),
            r.getEmpleadoPrestamo(),
            r.getEmpleadoDevolucion()
        });
    }
        tbl_Reporte.setModel(modelo);
    }//GEN-LAST:event_btn_CargarReporteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ListadoReportePrestamos().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_CargarReporte;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_Reporte;
    // End of variables declaration//GEN-END:variables
}
