/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.RolDAO;
import Model.Rol;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dell
 */
public class ListaRol extends javax.swing.JFrame {
    
    private DefaultTableModel modeloTabla;
    private RolDAO rolDAO = new RolDAO();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ListaRol.class.getName());

    /**
     * Creates new form ListaRol
     */
    public ListaRol() {
        initComponents();
        setLocationRelativeTo(null);
        
           modeloTabla = (DefaultTableModel) tbl_Rol.getModel();
        cargarDatos();
    }
    
    
    private void cargarDatos(){
        modeloTabla.setRowCount(0);
        List<Object>Rol = rolDAO.getAll();
        for(Object Rol_uncast : Rol){
            Rol rol = (Rol) Rol_uncast;
            modeloTabla.addRow(new Object[]{rol.getRolID(), rol.getRolDescripcion()});
        }
    
    }
    
    public void refrescarInfo(){
        cargarDatos();  
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Rol = new javax.swing.JTable();
        btn_Insertar = new javax.swing.JButton();
        btn_Actualizar = new javax.swing.JButton();
        txt_delete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbl_Rol.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "RolID", "RolDescripcion"
            }
        ));
        jScrollPane1.setViewportView(tbl_Rol);

        btn_Insertar.setText("Insertar");
        btn_Insertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_InsertarActionPerformed(evt);
            }
        });

        btn_Actualizar.setText("Actualizar");
        btn_Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ActualizarActionPerformed(evt);
            }
        });

        txt_delete.setText("Eliminar");
        txt_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_Insertar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Actualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_delete))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Insertar)
                    .addComponent(btn_Actualizar)
                    .addComponent(txt_delete))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_InsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_InsertarActionPerformed
        // TODO add your handling code here:
        
        FormularioRol formulario = new FormularioRol(this, true, "INS", 0);
        formulario.setVisible(true);
    }//GEN-LAST:event_btn_InsertarActionPerformed

    private void btn_ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ActualizarActionPerformed
        // TODO add your handling code here:
        
        int filaSeleccionada = tbl_Rol.getSelectedRow();
        if(filaSeleccionada == -1){
            JOptionPane.showMessageDialog(this, "Debe Seleccionar una fila", "Error", JOptionPane.ERROR_MESSAGE);
        
        }
        
        int RolID = (int) modeloTabla.getValueAt(filaSeleccionada, 0);
        
        FormularioRol formulario = new FormularioRol(this, true, "UPD", RolID);
        formulario.setVisible(true);
        
    }//GEN-LAST:event_btn_ActualizarActionPerformed

    private void txt_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_deleteActionPerformed
        // TODO add your handling code here:
        
        int filaSeleccionada = tbl_Rol.getSelectedRow();
        if(filaSeleccionada == -1){
            JOptionPane.showMessageDialog(this, "Debe Seleccionar una fila", "Error", JOptionPane.ERROR_MESSAGE);
        
        }
        
        int RolID = (int) modeloTabla.getValueAt(filaSeleccionada, 0);
        
        FormularioRol formulario = new FormularioRol(this, true, "DLT", RolID);
        formulario.setVisible(true);
        
    }//GEN-LAST:event_txt_deleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ListaRol().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Actualizar;
    private javax.swing.JButton btn_Insertar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_Rol;
    private javax.swing.JButton txt_delete;
    // End of variables declaration//GEN-END:variables
}
