/*Creado Por Zenia PAscual y Carlos Gamez
 */
package View;

import Controller.LibrosDAO;
import Model.Libros;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class ListadoLibros extends javax.swing.JFrame {
    private DefaultTableModel modeloTabla;
    private LibrosDAO librosDAO = new LibrosDAO();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ListadoLibros.class.getName());

    /**
     * Creates new form ListadoLibros
     */
    public ListadoLibros() {
        initComponents();
        setLocationRelativeTo(null);
        
        modeloTabla = (DefaultTableModel) tbl_Libros.getModel();
        cargarDatos();
    }
    
    
    private void cargarDatos(){
        modeloTabla.setRowCount(0);
        List<Object>Libros = librosDAO.getAll();
        for(Object Libros_uncast : Libros){
            Libros libros = (Libros) Libros_uncast;
            modeloTabla.addRow(new Object[]{libros.getLibrosID(), libros.getTitulo(), libros.getFechaPublicacion(), libros.getCategoriaID(), libros.getEdicion()});
        }
    
    }
    
    public void refrescarInfo(){
        cargarDatos();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Libros = new javax.swing.JTable();
        btn_Insertar = new javax.swing.JButton();
        btn_Actualizar = new javax.swing.JButton();
        txt_delete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Libros");

        tbl_Libros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "LibrosID", "Titulo", "FechaPublicacion", "CategoriaID", "Edicion"
            }
        ));
        jScrollPane1.setViewportView(tbl_Libros);

        btn_Insertar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Insertar.setText("Insertar");
        btn_Insertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_InsertarActionPerformed(evt);
            }
        });

        btn_Actualizar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Actualizar.setText("Actualizar");
        btn_Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ActualizarActionPerformed(evt);
            }
        });

        txt_delete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_delete.setText("Eliminar");
        txt_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_Insertar)
                        .addGap(104, 104, 104)
                        .addComponent(btn_Actualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_delete))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Insertar)
                    .addComponent(btn_Actualizar)
                    .addComponent(txt_delete))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_InsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_InsertarActionPerformed
        // TODO add your handling code here:
        
        FormularioLibros formulario = new FormularioLibros(this, true, "INS", 0);
        formulario.setVisible(true);
    }//GEN-LAST:event_btn_InsertarActionPerformed

    private void btn_ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ActualizarActionPerformed
        // TODO add your handling code here:
        
        int filaSeleccionada = tbl_Libros.getSelectedRow();
        if(filaSeleccionada == -1){
            JOptionPane.showMessageDialog(this, "Debe Seleccionar una fila", "Error", JOptionPane.ERROR_MESSAGE);
        
        }
        
        int LibrosID = (int) modeloTabla.getValueAt(filaSeleccionada, 0);
        
        FormularioLibros formulario = new FormularioLibros(this, true, "UPD", LibrosID);
        formulario.setVisible(true);
    }//GEN-LAST:event_btn_ActualizarActionPerformed

    private void txt_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_deleteActionPerformed
        // TODO add your handling code here:
        
        int filaSeleccionada = tbl_Libros.getSelectedRow();
        if(filaSeleccionada == -1){
            JOptionPane.showMessageDialog(this, "Debe Seleccionar una fila", "Error", JOptionPane.ERROR_MESSAGE);
        
        }
        
        int LibrosID = (int) modeloTabla.getValueAt(filaSeleccionada, 0);
        
        FormularioLibros formulario = new FormularioLibros(this, true, "DLT", LibrosID);
        formulario.setVisible(true);
    }//GEN-LAST:event_txt_deleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ListadoLibros().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Actualizar;
    private javax.swing.JButton btn_Insertar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_Libros;
    private javax.swing.JButton txt_delete;
    // End of variables declaration//GEN-END:variables
}
