/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View;
import Model.Empleados;
import View.ListadoAutores;
import View.ListadoLibros;
import View.ListaRol;
import View.ListadoCategorias;
import View.ListadoPrestamos;
import View.ListadoUsuarios;
import java.awt.Image;
import javax.swing.ImageIcon;
/**
 *
 * @author Dell
 */
public class Menu extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Menu.class.getName());

    /**
     * Creates new form Menu
     */
    private Empleados empleadoActual;
    
    public Menu(java.awt.Frame parent, boolean modal, Empleados empleado) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setVisible(true);

        this.empleadoActual = empleado;

        jLabelBiblioteca.setText("Bienvenido, " + empleado.getNombreEmpleado()
                             + " (" + empleado.getRolDescripcion() + ")");

        // Control de permisos por rol
        if (empleado.getRolID() != 1) {
        btn_Empleados.setEnabled(false);
        btn_Rol.setEnabled(false);
        btn_TipoUsuario.setEnabled(false);
        }
        
        ImageIcon iconoOriginal = new ImageIcon(getClass().getResource("/imagenes/Biblioteca.png"));
        Image imagenRedimensionada = iconoOriginal.getImage().getScaledInstance(45, 45, Image.SCALE_SMOOTH);
        jbl_Bibliteca.setIcon(new ImageIcon(imagenRedimensionada));
        
        System.out.println(getClass().getResource("/imagenes/Biblioteca.png"));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_Libros = new javax.swing.JButton();
        btn_Rol = new javax.swing.JButton();
        btn_Autores = new javax.swing.JButton();
        btn_Categoria = new javax.swing.JButton();
        jLabelBiblioteca = new javax.swing.JLabel();
        btn_TipoUsuario = new javax.swing.JButton();
        btn_Devoluiones = new javax.swing.JButton();
        btn_Ejemplares = new javax.swing.JButton();
        btn_Empleados = new javax.swing.JButton();
        btn_Prestamos = new javax.swing.JButton();
        btn_Usuarios = new javax.swing.JButton();
        jbl_Bibliteca = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Bienvendo a Nuestra Bibliteca");
        setBackground(new java.awt.Color(153, 255, 153));

        btn_Libros.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_Libros.setText("Libros");
        btn_Libros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LibrosActionPerformed(evt);
            }
        });

        btn_Rol.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_Rol.setText("Rol");
        btn_Rol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RolActionPerformed(evt);
            }
        });

        btn_Autores.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_Autores.setText("Autores");
        btn_Autores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AutoresActionPerformed(evt);
            }
        });

        btn_Categoria.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_Categoria.setText("Categorias");
        btn_Categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CategoriaActionPerformed(evt);
            }
        });

        jLabelBiblioteca.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelBiblioteca.setText("Biblioteca");

        btn_TipoUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_TipoUsuario.setText("TipoUsuario");
        btn_TipoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TipoUsuarioActionPerformed(evt);
            }
        });

        btn_Devoluiones.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Devoluiones.setText("Devoluciones");
        btn_Devoluiones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DevoluionesActionPerformed(evt);
            }
        });

        btn_Ejemplares.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Ejemplares.setText("Ejemplares");
        btn_Ejemplares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EjemplaresActionPerformed(evt);
            }
        });

        btn_Empleados.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Empleados.setText("Empleados");
        btn_Empleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EmpleadosActionPerformed(evt);
            }
        });

        btn_Prestamos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Prestamos.setText("Prestamos");
        btn_Prestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PrestamosActionPerformed(evt);
            }
        });

        btn_Usuarios.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Usuarios.setText("Usuarios");
        btn_Usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UsuariosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(97, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelBiblioteca, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(jbl_Bibliteca, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(115, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_Autores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_Libros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_TipoUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_Ejemplares, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_Prestamos, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_Rol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_Categoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_Devoluiones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_Empleados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_Usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(92, 92, 92))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbl_Bibliteca, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelBiblioteca))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Libros)
                    .addComponent(btn_Rol))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Autores)
                    .addComponent(btn_Categoria))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_TipoUsuario)
                    .addComponent(btn_Devoluiones))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Ejemplares)
                    .addComponent(btn_Empleados))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Prestamos)
                    .addComponent(btn_Usuarios))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_AutoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AutoresActionPerformed
        // TODO add your handling code here:
        
        new ListadoAutores().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_AutoresActionPerformed

    private void btn_LibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LibrosActionPerformed
        // TODO add your handling code here:
         new ListadoLibros().setVisible(true);
         this.dispose();
    }//GEN-LAST:event_btn_LibrosActionPerformed

    private void btn_RolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RolActionPerformed
        // TODO add your handling code here:
        new ListaRol().setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_btn_RolActionPerformed

    private void btn_CategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CategoriaActionPerformed
        // TODO add your handling code here:
        
        new ListadoCategorias().setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_btn_CategoriaActionPerformed

    private void btn_TipoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TipoUsuarioActionPerformed
        // TODO add your handling code here:
        new ListadoTipoUsuario().setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_btn_TipoUsuarioActionPerformed

    private void btn_DevoluionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DevoluionesActionPerformed
        // TODO add your handling code here:
        new ListadoDevoluciones().setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_btn_DevoluionesActionPerformed

    private void btn_EjemplaresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EjemplaresActionPerformed
        // TODO add your handling code here:
        new ListadoEjemplares().setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_btn_EjemplaresActionPerformed

    private void btn_EmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EmpleadosActionPerformed
        // TODO add your handling code here:
        new ListadoEmpleados().setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_btn_EmpleadosActionPerformed

    private void btn_PrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PrestamosActionPerformed
        // TODO add your handling code here:
        new ListadoPrestamos().setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_btn_PrestamosActionPerformed

    private void btn_UsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UsuariosActionPerformed
        // TODO add your handling code here:
        new ListadoUsuarios().setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_btn_UsuariosActionPerformed
   
    /**this.setVisible(false);
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Autores;
    private javax.swing.JButton btn_Categoria;
    private javax.swing.JButton btn_Devoluiones;
    private javax.swing.JButton btn_Ejemplares;
    private javax.swing.JButton btn_Empleados;
    private javax.swing.JButton btn_Libros;
    private javax.swing.JButton btn_Prestamos;
    private javax.swing.JButton btn_Rol;
    private javax.swing.JButton btn_TipoUsuario;
    private javax.swing.JButton btn_Usuarios;
    private javax.swing.JLabel jLabelBiblioteca;
    private javax.swing.JLabel jbl_Bibliteca;
    // End of variables declaration//GEN-END:variables
}
